#!/bin/bash
# 部署 CDK stack 并导出环境信息到 .env.deploy
set -euo pipefail

REGION="${1:?Usage: ./setup.sh <region> <profile>}"
PROFILE="${2:?Usage: ./setup.sh <region> <profile>}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/deploy"

PATH=".venv/bin:$PATH" cdk deploy -c region="$REGION" --profile "$PROFILE" --require-approval never "${@:3}"

# 导出 stack outputs
echo "→ 导出部署信息..."
OUTPUTS=$(aws cloudformation describe-stacks --stack-name OpenClawOrchestrator \
  --query 'Stacks[0].Outputs[*].[OutputKey,OutputValue]' --output text \
  --profile "$PROFILE" --region "$REGION")

# 保留 bind-domain.sh 设置的 DASHBOARD_URL（如果存在）
EXISTING_DASHBOARD_URL=""
if [ -f "$SCRIPT_DIR/.env.deploy" ]; then
  EXISTING_DASHBOARD_URL=$(grep '^DASHBOARD_URL=https://' "$SCRIPT_DIR/.env.deploy" | head -1 || true)
fi

cat > "$SCRIPT_DIR/.env.deploy" << EOF
# Auto-generated by setup.sh — $(date -Iseconds)
REGION=$REGION
PROFILE=$PROFILE
$(echo "$OUTPUTS" | awk '{
  key=$1
  out=""
  for(i=1;i<=length(key);i++){
    c=substr(key,i,1)
    if(c ~ /[A-Z]/ && i>1) out=out"_"
    out=out toupper(c)
  }
  print out"="$2
}')
EOF

# Restore custom DASHBOARD_URL (set by bind-domain.sh) if it was HTTPS
if [ -n "$EXISTING_DASHBOARD_URL" ]; then
  sed -i '' '/^DASHBOARD_URL=/d' "$SCRIPT_DIR/.env.deploy"
  echo "$EXISTING_DASHBOARD_URL" >> "$SCRIPT_DIR/.env.deploy"
fi

# 查询 API Key value (stack output 只有 ID)
API_KEY_ID=$(grep '^API_KEY_ID=' "$SCRIPT_DIR/.env.deploy" | cut -d= -f2)
if [ -n "$API_KEY_ID" ]; then
  API_KEY=$(aws apigateway get-api-key --api-key "$API_KEY_ID" --include-value \
    --query 'value' --output text --profile "$PROFILE" --region "$REGION")
  echo "API_KEY=$API_KEY" >> "$SCRIPT_DIR/.env.deploy"
fi

echo "✓ 环境信息已保存到 .env.deploy"
cat "$SCRIPT_DIR/.env.deploy"
